services:
  backend:
    mem_limit: 8g
    build: ./backend
    volumes:
      - ./logs:/code/logs
      - ./backend:/code/backend
      - ./data:/code/data
      - ./models:/code/models
      - ./reports:/code/reports
      - ./uploads:/code/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - HF_TOKEN=${HF_TOKEN:-}
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    mem_limit: 6g
    build: ./backend
    command: celery -A backend.app.celery_app.celery_app worker --loglevel=info
    volumes:
      - ./logs:/code/logs
      - ./backend:/code/backend
      - ./data:/code/data
      - ./models:/code/models
      - ./reports:/code/reports
      - ./uploads:/code/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend